package com.bank.islamic.profitequalizationreserve;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Profit Equalization Reserve
 *
 * Business Area:      Deposits and Investment Accounts
 * Business Domain:    Profit Management
 * Functional Pattern: Manage
 * Asset Type:         Profit Equalization Reserve
 * Control Record:     Profit Equalization Reserve Management Plan
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Profit Equalization Reserve — BIAN Semantic API")
                .description("Service Domain 'Profit Equalization Reserve' (Manage pattern) "
                        + "operating on the 'Profit Equalization Reserve Management Plan' control record.")
                .version("0.1.0"));
    }
}
