apiVersion: v2
name: isb-profit-equalization-reserve
description: "BIAN Service Domain: Profit Equalization Reserve (Manage pattern, Deposits and Investment Accounts)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - islamic-banking
  - manage
annotations:
  isb/business-area: "Deposits and Investment Accounts"
  isb/business-domain: "Profit Management"
  isb/asset-type: "Profit Equalization Reserve"
  isb/control-record: "Profit Equalization Reserve Management Plan"
